### ISSUE TITLE
Pygame library

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G2#66]
Hi group 2,
 You used Pygame library. It's great to see that you have made animation of elastic collision there. It's new for me. Could you share more description or any resources to learn more about Pygame?

**Comment by Mosaddeq107** [comment]
Pygame is a popular Python library used for developing 2D games and multimedia applications. It provides modules for you to access the video display, play sounds, handle user input, and manage multimedia resources like images and fonts. Pygame is widely used by developers and hobbyists due to its simplicity and ease of use.

**Comment by Mosaddeq107** [comment]
For more information, you can look into our codes or take some examples from google.

**Comment by Pranjal-Srivastava-2023** [comment]
To use pygame library type "pip install pygame" in terminal of VS code and then import pygame. It doesn't work on Jupyter notebook generally.

**Comment by Pranjal-Srivastava-2023** [comment]
Alternatively, you can also use Vpython or even matplotlib. But I found the animation to be much smoother using pygame.

**Comment by pratibha77118** [comment]
Oh I tried in Jupyter Notebook. So I did not work for me. Thanks!
